---
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    authc:
      basic_internal_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
      saml_auth_domain:
        http_enabled: true
        transport_enabled: false
        order: 0
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              enable_ssl: false
              verify_hostnames: false
              metadata_url: https://seems.okta.com/app/exkhmvkssEzGVHwyu696/sso/saml/metadata
              entity_id: http://www.okta.com/exkhmvkssEzGVHwyu696
            sp:
              entity_id: opensearch-saml
              forceAuthn: true
            kibana_url: https://10.10.20.10:5601/
            roles_key: Roles
            exchange_key: 'asdamjeraonpiwetboniwtuonqweitbvqpweitmqowpecpqwecqpwijpo'
        authentication_backend:
          type: noop